### ISSUE TITLE
using two image-uploaders on single page has issues

### ISSUE THREAD

**Issue by dmsherazi** [responsiv/uploader-plugin#66] opened 2020-06-25 15:01 UTC
I am having issues when using two imageUploder components, One as single-image and the other as multi-image. The images get uploaded but only a single image is attached to both in db

```
[imageUploader site_image]
placeholderText = "Click or drag site images to upload"
maxSize = 5
fileTypes = ".gif,.jpg,.jpeg,.png"

modelClass = "------"
modelKeyColumn = "site_image"
deferredBinding = 1

[imageUploader images]
placeholderText = "Click or drag site images to upload"
maxSize = 5
fileTypes = ".gif,.jpg,.jpeg,.png"

modelClass = "------"
modelKeyColumn = "images"
deferredBinding = 1
```

init is done as 
```
function onInit(){
 $obj =new Spot\Models\myModel;
    $this->images->bindModel('site_image',$obj);
    $this->site_image->bindModel('images',$obj);
}
```

and here is the html part
```
    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">{{'Site image'|__}}</label>
                        <div class="col-lg-9 col-xl-6">
                            <div class="kt-site_image kt-avatar--outline" id="kt_site_image">
                                {% partial site_image ~ '::image-single' %}
                            </div>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-xl-3 col-lg-3 col-form-label">{{'Board Images'|__}}</label>
                        <div class="col-lg-9 col-xl-6">
                            <div class="kt-avatar kt-avatar--outline" id="kt_images">
                                {% partial images ~ '::image-multi' %}
                            </div>
                        </div>
                    </div>
```

**Comment by LukeTowers** [comment] 2020-06-25 16:13
Duplicate of https://github.com/responsiv/uploader-plugin/issues/59. Make sure you have https://github.com/responsiv/uploader-plugin/commit/3a0df39c24c3d622c9f19024154d0fd524951940 applied locally.

**Closed as completed by LukeTowers** 2020-06-25 16:13 UTC
Labels: duplicate
